#!/bin/bash
# (c) Jochen Puchalla 2009

OQUAL=4
source "$(kde4-config --localprefix)/share/config/kwerc"
QUALITY=$OQUAL

test -z "$1" && echo -e "\nusage: oggdrop-lx4 filename(s)\n" && exit

until [ -z "$1" ]  # Until all parameters are used up...
do
	if [ -f "$1" ]
	then
		export EXTRA=""
		if [ "${1: -4}" = ".ogg" ]
		then anytowav4 -dontask "$1"
		else if [ "${1: -4}" = ".OGG" ]
		then anytowav4 -dontask "$1"
		else audioconvert4 -t o -q $QUALITY -dontask "$1"
		fi
		fi
	fi
	shift
done



